# Site settings
title: Underconstruction
email: peilin.yu.0@gmail.com
description: Personal Web for Peilin.
baseurl: "/eventually-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
github_url: https://github.com/dotpyu
linkedin_url: https://www.linkedin.com/in/chungking


# Build settings
markdown: kramdown
